//------------------------------------------------------------------------------
// <auto-generated>
// Strings.cs
//
// Do not edit directly. This file has been generated by ResXFileScriptGenerator v0.7.0.0.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;

namespace Vtj.Contest {

    /// <summary>Strings resources class</summary>
    [GeneratedCodeAttribute("ResXInternalScriptGenerator", "0.7.0.0")]
    [Resources]
    internal static class Strings {

        public static readonly string CutScene_1_1 = null;

        public static readonly string CutScene_1_2 = null;

        public static readonly string CutScene_1_3 = null;

        public static readonly string CutScene_1_4 = null;

        public static readonly string CutScene_1_5 = null;

        public static readonly string CutScene_1_6 = null;

        public static readonly string CutScene_2_1 = null;

        public static readonly string CutScene_2_2 = null;

        public static readonly string CutScene_2_3 = null;

        public static readonly string CutScene_3_1 = null;

        public static readonly string CutScene_3_2 = null;

        public static readonly string CutScene_3_3 = null;

        public static readonly string CutScene_4_1 = null;

        public static readonly string CutScene_5_1 = null;
    }
}
